name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH Commands
        uses: fifsky/ssh-action@v0.0.4
        with:
          command: |
            cd ${{ secrets.REMOTE_TARGET }}
            git pull origin master
            composer install --no-dev --optimize-autoloader --prefer-dist
            php artisan migrate --force
            npm install
            npm run prod
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

